config/routes.rb
Rails.application.routes.draw do
  
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  
  resources :users, only: [:new, :create]

  resources :lists do
    resources :items
  end

  root 'lists#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :list
    validates :description, presence: true

    STATUS = {
        :incomplete => 0,
        :complete => 1
    }

    def complete?
        self.status == STATUS[:complete]
    end

    def incomplete?
        self.status == STATUS[:incomplete]
    end
end

app/models/list.rb
class List < ApplicationRecord
    has_many :items

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password 
    before_validation :downcase_email

    validates :email, :presence => true
    validates :email, :uniqueness => true

    private
    def downcase_email
        self.email = email.downcase if email.present?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

    def authentication_required
      if !logged_in?
        redirect_to login_path
      end
    end

    def logged_in?
      !!current_user
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
      if @item.save 
        redirect_to list_path(@list)
      else
        render 'lists/show'
      end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to list_path(@item.list)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_path(@item.list)
  end

  private 
    def item_params
      params.require(:item).permit(:description, :status)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :authentication_required
    
    def index 
        @list = List.new
        @lists = List.all
    end 

    def show
        @list = List.find(params[:id])
        @item = Item.new
    end

    def create 
       @list = List.new(list_params)
      if @list.save
        redirect_to list_path(@list)
      else 
        @lists = List.all
        render :index
      end
    end 

    private
        def list_params
            params.require(:list).permit(:name)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
    end 

    def create 
        user = User.find_by(email: params[:email])
        if user && user.authenticate(:params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            render login_path
        end
    end

    def destroy
        reset_session
        redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else 
            render :new
        end
    end

    private 
        def user_params
            params.require(:user).permit(:email, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def li_class_for_item(item)
        "completed" if item.complete?
    end

    def li_for_item(item)
        content_tag_for :li, item, :class => li_class_for_item(item) do
            yield
        end
    end

    def form_for_item_status(item)
        form_for([@list, item]) do |f|
            f.check_box :status, :class => "toggle", :checked => item.complete?
        end
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
    <div class="view">
        <%= form_for_item_status(item) %>

        <label><%= item.description %></label>

        <%= button_to "x", list_item_path(item.list, item), :method => "delete", :class => "destroy" %>

    </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoMVC</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">
	<header class="header">
		<h1>todo lists</h1>
          <%= form_for(@list) do |f| %>
            <%= f.text_field :name, class: "new-todo", placeholder: (@list.errors.full_messages_for(:name).first || "make a new list") %>
            <%= f.submit style: "visibility: hidden;", data: "disable_with: false"%>
          <% end %>
	</header>
	<section class="main">
		<ul class="todo-list">
        <% @lists.each do |list| %>
          <li>
            <div class="view">
              <label><a href="#"><%= link_to list.name, list_path(list) %></a></label>
            </div>
          </li>
        <% end %>
        </ul>
	</section>
	<footer class="footer">
	</footer>
</section>

<footer class="info">
  <p>You're logged in as <%= current_user.email %></p>
	<p><%= link_to 'Logout', logout_path %></p>		
</footer>

app/views/lists/show.html.erb
<section class="todoapp">
	<header class="header">
		<h1><%= @list.name %></h1>
		<%= form_for([@list, @item]) do |f| %>
            <%= f.text_field :description, class: "new-todo", placeholder: (@item.errors.full_messages_for(:description).first || "add a new item") %>
            <%= f.submit style: "visibility: hidden;", data: "disable_with: false"%>
          <% end %>
	</header>
	<section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
		<ul class="todo-list">
        <%= render :collection => @list.items, :partial => "items/item_li", :as => :item %>
    </ul>
	</section>
	<footer class="footer">
	</footer>
</section>

app/views/users/new.html.erb
<section class="todoapp">
	<header class="header">
		<h1>Signup</h1>

        <%= form_for(@user) do |f| %>
            <%= f.text_field :email, class: "new-todo", placeholder: "register with your email" %>
			<%= f.text_field :password, class: "new-todo", placeholder: "create password" %>
			<%= f.submit %>
        <% end %>
          
	</header>
	
	<footer class="footer">
	</footer>
</section>